version: '2'
services:
    php:
        container_name: php_fpm
        build: ./php-fpm
        volumes:
            - ./symfony:/var/www/symfony
            - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./symfony:/var/www/symfony
            - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        container_name: mysql
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"